name: walletiq
services:

  # postgreSql
  postgres:
    image: postgres:16-alpine
    container_name: walletiq-postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=walletiq
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password8080
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - walletiq-network

  # redis
  redis:
    image: redis:alpine
    container_name: walletiq-redis
    restart: on-failure
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - walletiq-network

  #zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: walletiq-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - walletiq-network

volumes:
  postgres-data:
  redis-data:

networks:
  walletiq-network:
    driver: bridge