name: walletiq
services:

  # postgresql
  postgres:
    image: postgres:16-alpine
    container_name: walletiq-postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=walletiq
      - POSTGRES_PASSWORD=walletiq
      - POSTGRES_DB=walletiq
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:alpine
    container_name: walletiq-redis
    restart: on-failure
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: